services:
  php:
    container_name: php
    image: registry.digitalocean.com/sylius/sales-demo-php:$GITHUB_SHA
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://sylius:${MYSQL_PASSWORD}@mysql/sylius_prod
      MAILER_DSN: null://localhost
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: EDITME
      HOME_HOSTNAME: ${HOME_HOSTNAME:-home.localhost}
      FASHION_HOSTNAME: ${FASHION_HOSTNAME:-fashion.localhost}
      SENTRY_DSN: ${SENTRY_DSN:?SENTRY_DSN is not set or empty}
      MESSENGER_TRANSPORT_DSN: sync://
      WKHTMLTOPDF_PATH: /usr/local/bin/wkhtmltopdf
      WKHTMLTOIMAGE_PATH: /usr/local/bin/wkhtmltoimage
    volumes:
      - ./sylius/var/sessions:/srv/sylius/var/sessions:rw
      - ./sylius/public/media:/srv/sylius/public/media:rw
    networks:
      - sylius

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: sylius_prod
      MYSQL_USER: sylius
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    networks:
      - sylius

  nginx:
    container_name: nginx
    image: registry.digitalocean.com/sylius/sales-demo-nginx:$GITHUB_SHA
    depends_on:
      - php
    volumes:
      - ./sylius/public/media:/srv/sylius/public/media:ro
    networks:
      - sylius
    ports:
      - 80:80

networks:
  sylius:
    driver: bridge
