kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sylius.fullname" . }}-media
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sylius.fullname" . }}-sessions
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
