apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sylius.fullname" . }}-envs
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sylius.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envs }}
  {{ $key }}: {{ $value | toString }}
  {{- end }}
  {{ if not .Values.envs.DATABASE_URL -}}
  DATABASE_URL: mysql://sylius:sylius@{{ printf "%s-%s" .Release.Name "mysql" | toString -}}/sylius
  {{ end }}
