imports:
    - { resource: "../vendor/sylius/sylius/src/Sylius/Behat/Resources/config/services.xml" }
    - { resource: "../vendor/sylius/invoicing-plugin/tests/Behat/Resources/services.xml" }
    - { resource: "../vendor/sylius/refund-plugin/tests/Behat/Resources/services.xml" }
    - { resource: "../vendor/sylius/plus/tests/Behat/Resources/services.xml" }
    - { resource: "services/test/behat.xml" }

services:
    Tests\Sylius\RefundPlugin\Behat\Services\Generator\FailedCreditMemoGenerator:
        decorates: 'Sylius\RefundPlugin\Generator\CreditMemoGeneratorInterface'
        arguments:
            - '@Tests\Sylius\RefundPlugin\Behat\Services\Generator\FailedCreditMemoGenerator.inner'

    Tests\Sylius\RefundPlugin\Behat\Services\Factory\FailedRefundPaymentFactory:
        decorates: 'sylius_refund.factory.refund_payment'
        arguments:
            - '@Tests\Sylius\RefundPlugin\Behat\Services\Factory\FailedRefundPaymentFactory.inner'

sylius_api:
    enabled: true
