winzou_state_machine:
    sylius_order_checkout:
        transitions:
            complete:
                from: [cart, addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped]
                to: completed

bitbag_sylius_adyen:
    logger: true
    supported_types: ~

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@BitBagSyliusCmsPlugin/Form/ckeditor_widget.html.twig'
